swagger: '2.0'
info:
  description: Api Rest for CSC
  version: 1.0.0
  title: CSC Api Rest
host: 192.168.20.7
basePath: ''
schemes:
  - http
paths:
  '/ws/{id}':
    get:
      summary: Request the IP address of a websocket
      description: ''
      parameters:
        - name: id
          in: path
          description: ID of the client
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: websocket found
          schema:
            $ref: '#/definitions/WebsocketAddress'
        '404':
          description: websocket not created or found
          
  '/ws/connect/{pseudo}/{password}':
    get:
      summary: Request the password and the pseudo 
      description: ''
      parameters:
        - name: pseudo
          in: path
          description: pseudo of client
          required: true
          type: string
          
        - name : password
          in: path
          description: password
          required: true
          type: string
          
      produces:
        - application/json
      responses:
        '200':
          description: websocket found
          schema:
            $ref: '#/definitions/WebsocketAddress'
        '404':
          description: websocket not created or found
  
    
definitions:
  WebsocketAddress:
    type: object
    properties:
      uri:
        type: string
